# Generated by Django 4.1 on 2022-09-02 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_follow_prevent_self_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='is_adult',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('birthday__lte', datetime.date(2004, 9, 6))), name='is_adult'),
        ),
    ]
