# Generated by Django 4.1 on 2022-09-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_like_post_like_to_post_like_unique_like_to_the_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='like', to='user.like'),
        ),
    ]
